# Funding Options

# GitHub Sponsors
# github: username

# Open Collective
# open_collective: project-name

# Community funding
# This is an open-source security tool. 
# Consider supporting the underlying projects:

# OWASP ZAP - https://owasp.org/donate/
# Nuclei - https://github.com/sponsors/projectdiscovery
# GitHub Actions - Part of GitHub platform

# If this tool has helped your organization, consider:
# - Contributing back improvements
# - Starring the repository 
# - Sharing with the community
# - Reporting issues to help improve it