name: Question or Help
description: Ask a question or get help with setup
title: "[QUESTION] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using this security scanning tool? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What area is your question about?
      options:
        - Setup and Installation
        - Workflow Configuration
        - Security Scan Results
        - GitHub Integration
        - Troubleshooting
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context and What You've Tried
      description: Provide context and any solutions you've already attempted
      placeholder: |
        I'm trying to...
        I've already tried...
        The documentation suggests...

  - type: textarea
    id: environment
    attributes:
      label: Environment (if applicable)
      description: If relevant to your question, share environment details
      placeholder: |
        - Repository type: Public/Private
        - GitHub Actions runner: ubuntu-latest
        - Project type: Node.js/Python/etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have read the README.md documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
        - label: I have checked the Contributing guidelines
          required: false